CREATE TABLE dashboard (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE tracked_player (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashboard_id BIGINT NOT NULL,
    region       VARCHAR(255) NOT NULL,
    game_name    VARCHAR(255) NOT NULL,
    tag_line     VARCHAR(255) NOT NULL,
    puuid        VARCHAR(255) NOT NULL,
    CONSTRAINT fk_tracked_player_dashboard
        FOREIGN KEY (dashboard_id) REFERENCES dashboard (id) ON DELETE CASCADE,
    CONSTRAINT uk_tracked_player_dashboard_puuid UNIQUE (dashboard_id, puuid)
);
