CREATE TABLE lp_snapshot (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id  BIGINT NOT NULL,
    lp         INTEGER NOT NULL,
    timestamp  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_lp_snapshot_player
        FOREIGN KEY (player_id) REFERENCES tracked_player (id) ON DELETE CASCADE
);

CREATE INDEX idx_lp_snapshot_player_timestamp ON lp_snapshot (player_id, timestamp);
