spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lp_leaderboard
    username: lp_user
    password: lp_password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

riot:
  api-key: ${RIOT_API_KEY}

logging:
  level:
    org.springframework: INFO